training:
  batch_size: 128
  n_epochs: 3
  ngpu: 1
  iter_log: 1000
  iter_save: 100
  exp_id: "background_attr_clf"
  out_dir: "/atlas/u/madeline/multi-fairgen/src/classification/"
  data_dir: "/atlas/u/madeline/multi-fairgen/data/"

data:
  dataset: "SplitMNIST"
  subset: false
  image_size: 28
  channels: 1
  random_flip: false
  x_space: true
  digits: [0, 7]
  digit_percs: [0.5, 0.5]
  flipped_digits: [0, 7]
  flipped_digit_percs: [0.5, 0.5]
  include_all: true
  perc: 1.0
  num_workers: 4

model:
  name: "mlp"
  spectral_norm: true
  batch_norm: true
  in_dim: 784
  h_dim: 100
  dropout: 0.1
  n_classes: 2

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0002
  beta1: 0.9
  amsgrad: false

loss:
  name: "cross_entropy"