training:
  batch_size: 128
  n_epochs: 10
  ngpu: 1
  iter_log: 1000
  iter_save: 100
  exp_id: "mnist_same_bkgd_z"
  out_dir: "/atlas/u/madeline/multi-fairgen/src/classification/"
  data_dir: "/atlas/u/madeline/multi-fairgen/data/"

data:
  dataset: "MNIST"
  subset: true
  x_space: false
  perc: 0.5
  image_size: 28
  channels: 1
  random_flip: false
  num_workers: 4

model:
  name: "resnet"
  spectral_norm: true
  batch_norm: true
  in_dim: 784
  h_dim: 100
  dropout: 0.1
  n_classes: 2

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0002
  beta1: 0.9
  amsgrad: false

loss:
  name: "cross_entropy"