training:
  batch_size: 128
  n_epochs: 20
  ngpu: 1
  iter_log: 1000
  iter_save: 100
  exp_id: "da_x_dre_cifar_extreme"
  out_dir: "/atlas/u/kechoi/multi-fairgen/src/classification/results/"
  data_dir: "/atlas/u/kechoi/multi-fairgen/data/"

data:
  dataset: "DADRE_CIFAR10"
  subset: false
  x_space: true
  input_size: 3072
  image_size: 32
  channels: 3
  perc: 1.0
  mus: [0, 3]
  class_idx: 20
  num_workers: 4

model:
  name: "resnet20"
  spectral_norm: true
  batch_norm: true
  in_dim: 3072
  h_dim: 200
  dropout: 0.1
  n_classes: 1

optim:
  weight_decay: 0.0005
  optimizer: "Adam"
  lr: 0.0002
  beta1: 0.9
  amsgrad: false

loss:
  name: "bce"
  alpha: 0.01