training:
  batch_size: 100
  n_epochs: 200
  ngpu: 1
  log_interval: 100
  iter_save: 100
  exp_id: "mnist_perc0.25"
  out_dir: "/path/to/multi-fairgen/src/flows/results/"
  data_dir: "/path/to/multi-fairgen/data/"

sampling:
  generate: true
  fair: true
  n_samples: 3000
  encode: false

data:
  dataset: "MNIST_combined"
  subset: false
  perc: 0.25
  digits: [0,7]
  digit_percs: [0.2, 0.8]
  flipped_digits: [0, 7]
  flipped_digit_percs: [0.5, 0.5]
  image_size: 28
  channels: 1
  random_flip: false
  x_space: false
  class_idx: 20
  num_workers: 4
  flip_toy_var_order: true

model:
  name: "maf"
  dropout: 0.1
  n_classes: 2
  n_blocks: 5
  n_components: 1
  input_size: 784
  hidden_size: 1024
  n_hidden: 1
  activation_fn: 'relu'
  input_order: 'sequential'
  conditional: false
  no_batch_norm: false
  cond_label_size: 10
  ema: false

dre:
  alpha: 0.06

sampling:
  n_samples: 50000
  sir: 1000

optim:
  weight_decay: 0.000001
  optimizer: "Adam"
  lr: 0.0001
  beta1: 0.9
  amsgrad: false
  eps: 0.00000001

loss:
  name: "cross_entropy"