training:
  batch_size: 128
  n_epochs: 20
  ngpu: 1
  iter_log: 1000
  iter_save: 100
  exp_id: "cifar10_attr"
  out_dir: "/atlas/u/kechoi/multi-fairgen/src/classification/results/"
  data_dir: "/atlas/u/kechoi/multi-fairgen/data/"

data:
  dataset: "attrCIFAR10"
  subset: false
  x_space: true
  channels: 3
  image_size: 32
  perc: 1.0
  mus: [0, 3]
  class_idx: 20
  num_workers: 4
  rho: 0.9
  input_size: 3072

model:
  name: "resnet"
  spectral_norm: true
  batch_norm: true
  in_dim: 32
  h_dim: 500
  dropout: 0.1
  n_classes: 1

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0002
  beta1: 0.9
  amsgrad: false

loss:
  name: "bce"
  alpha: 0.01