training:
  batch_size: 128
  n_epochs: 10
  ngpu: 1
  iter_log: 1000
  iter_save: 100
  exp_id: "cifar_glow_z"
  out_dir: "/atlas/u/kechoi/multi-fairgen/src/classification/results/"
  data_dir: "/atlas/u/kechoi/multi-fairgen/data/"

data:
  dataset: "ZCIFAR10"
  subset: false
  x_space: false
  input_size: 768
  perc: 1.0
  mus: [0, 3]
  class_idx: 20
  num_workers: 4
  rho: 0.9

model:
  name: "mlp"
  spectral_norm: true
  batch_norm: true
  in_dim: 768
  h_dim: 100
  dropout: 0.1
  n_classes: 1

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0001
  beta1: 0.9
  amsgrad: false

loss:
  name: "bce"
  alpha: 0.01