training:
  batch_size: 32
  n_epochs: 100
  ngpu: 1
  iter_log: 1000
  iter_save: 100
  exp_id: "omniglot_mix_baseline_aug5"
  out_dir: "/atlas/u/kechoi/multi-fairgen/src/classification/results/"
  data_dir: "/atlas/u/kechoi/multi-fairgen/data/"

data:
  dataset: "Omniglot"
  subset: false
  x_space: true
  synthetic: true
  augment: true
  input_size: 784
  image_size: 28
  channels: 1
  perc: 1.0
  mus: [0, 3]
  class_idx: 20
  num_workers: 4

model:
  name: "cnn"
  baseline: true
  spectral_norm: true
  batch_norm: true
  in_dim: 784
  h_dim: 200
  dropout: 0.1
  n_classes: 1

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.001
  beta1: 0.9
  amsgrad: false

loss:
  name: "cross_entropy"
  alpha: 0.01