training:
  batch_size: 128
  n_epochs: 200
  ngpu: 1
  iter_log: 1000
  iter_save: 100
  exp_id: "mi_joint_flow_d40_alpha0.5"
  out_dir: "/atlas/u/kechoi/multi-fairgen/src/classification/results/"
  data_dir: "/atlas/u/kechoi/multi-fairgen/data/"

data:
  dataset: "MI"
  subset: false
  x_space: true
  input_size: 40
  perc: 1.0
  mus: [0, 3]
  class_idx: 20
  num_workers: 4
  rho: 0.95

model:
  name: "flow_mlp"
  spectral_norm: true
  batch_norm: true
  in_dim: 40
  h_dim: 200
  dropout: 0.1
  n_classes: 1

optim:
  weight_decay: 0.0005
  optimizer: "Adam"
  lr: 0.0002
  beta1: 0.9
  amsgrad: false

loss:
  name: "joint"
  alpha: 0.5